# SPDX-License-Identifier: Apache-2.0
# Cairn qmlformat settings. Four-space indent like .clang-format and
# .editorconfig; nothing reordered, so a file reads in the order it was
# written. Check a file without changing it:
#   /usr/lib64/qt6/bin/qmlformat file.qml | diff - file.qml
[General]
IndentWidth=4
UseTabs=false
MaxColumnWidth=-1
NormalizeOrder=false
NewlineType=native
SemicolonRule=always
